### ISSUE TITLE
12.0.1不起作用

### ISSUE THREAD

**Issue by Haohao5** [wy414012/RTL8168_8111#1]
是把RealtekRTL8111.kext覆盖原作者的2.4.2版本吗,在Monterey12.0.1下无法成功驱动

**Comment by wy414012** [comment]
@Haohao5 使用过原版2.4.2版本的，需要断开网口连接，与设备电源五分钟后才可以驱动，因为原版修改了一些默认值，导致更换其它驱动后网卡地址变成00:00:00:00 无法驱动！
